apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-e
  labels:
    app: web-service-e
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service-e
  template:
    metadata:
      labels:
        app: web-service-e
    spec:
      containers:
        - name: web-container
          image: your-registry/web-service-e:1.2.3
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api-url
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
