# ---------------------------------------------
# Deployment configuration for web-service-f
# WARNING: This file has grown over time.
# Many old configs are preserved for historical reasons.
# ---------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-f
  labels:
    app: web-service-f
# metadata.annotations:
#   last-applied-version: v0.8.1
#   maintainer: "ops@company.com"

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service-f
  template:
    metadata:
      labels:
        app: web-service-f
    spec:
      containers:
        - name: web-container
          image: your-registry/web-service-f:1.2.3
          ports:
            - containerPort: 3000
          #          - containerPort: 8080  # Old port, do not re-enable
          #          - containerPort: 80    # Used during NGINX reverse proxy test
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api-url
            - name: LOG_LEVEL
              value: "info"
          #            - name: LOG_LEVEL
          #              value: "debug"
          #            - name: LEGACY_FLAG
          #              value: "true"
          #            - name: DEPRECATED_TIMEOUT
          #              value: "5000"
          #            - name: EXPERIMENTAL_FEATURE
          #              value: "true"

          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          #            requests:
          #              cpu: "100m"
          #              memory: "256Mi"
          #            limits:
          #              cpu: "500m"
          #              memory: "512Mi"
          #            limits:
          #              cpu: "1"
          #              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          #            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
#            timeoutSeconds: 2
#            successThreshold: 1
