name: Run Gradle Tests

on:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/test
            build/test-results/test

      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          artifact: test-reports
          name: Gradle Tests
          path: test-results/test/*.xml
          reporter: java-junit
