name: Run Gradle Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@cdd725f5e5ef88b3e5de84d0889672221fbee4bf # v4.1.1

      - name: Set up JDK 23
        uses: actions/setup-java@6c36101334f9db8d7d7f2628c08fa432eb60c718 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test
